/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrongRouteImport } from './routes/wrong'
import { Route as RealizedRouteImport } from './routes/realized'
import { Route as PromiseRouteImport } from './routes/promise'
import { Route as MissRouteImport } from './routes/miss'
import { Route as HeartRouteImport } from './routes/heart'
import { Route as ForYouRouteImport } from './routes/for-you'
import { Route as IndexRouteImport } from './routes/index'

const WrongRoute = WrongRouteImport.update({
  id: '/wrong',
  path: '/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const RealizedRoute = RealizedRouteImport.update({
  id: '/realized',
  path: '/realized',
  getParentRoute: () => rootRouteImport,
} as any)
const PromiseRoute = PromiseRouteImport.update({
  id: '/promise',
  path: '/promise',
  getParentRoute: () => rootRouteImport,
} as any)
const MissRoute = MissRouteImport.update({
  id: '/miss',
  path: '/miss',
  getParentRoute: () => rootRouteImport,
} as any)
const HeartRoute = HeartRouteImport.update({
  id: '/heart',
  path: '/heart',
  getParentRoute: () => rootRouteImport,
} as any)
const ForYouRoute = ForYouRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-you': typeof ForYouRoute
  '/heart': typeof HeartRoute
  '/miss': typeof MissRoute
  '/promise': typeof PromiseRoute
  '/realized': typeof RealizedRoute
  '/wrong': typeof WrongRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-you': typeof ForYouRoute
  '/heart': typeof HeartRoute
  '/miss': typeof MissRoute
  '/promise': typeof PromiseRoute
  '/realized': typeof RealizedRoute
  '/wrong': typeof WrongRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-you': typeof ForYouRoute
  '/heart': typeof HeartRoute
  '/miss': typeof MissRoute
  '/promise': typeof PromiseRoute
  '/realized': typeof RealizedRoute
  '/wrong': typeof WrongRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-you'
    | '/heart'
    | '/miss'
    | '/promise'
    | '/realized'
    | '/wrong'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-you'
    | '/heart'
    | '/miss'
    | '/promise'
    | '/realized'
    | '/wrong'
  id:
    | '__root__'
    | '/'
    | '/for-you'
    | '/heart'
    | '/miss'
    | '/promise'
    | '/realized'
    | '/wrong'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForYouRoute: typeof ForYouRoute
  HeartRoute: typeof HeartRoute
  MissRoute: typeof MissRoute
  PromiseRoute: typeof PromiseRoute
  RealizedRoute: typeof RealizedRoute
  WrongRoute: typeof WrongRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrong': {
      id: '/wrong'
      path: '/wrong'
      fullPath: '/wrong'
      preLoaderRoute: typeof WrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realized': {
      id: '/realized'
      path: '/realized'
      fullPath: '/realized'
      preLoaderRoute: typeof RealizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promise': {
      id: '/promise'
      path: '/promise'
      fullPath: '/promise'
      preLoaderRoute: typeof PromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miss': {
      id: '/miss'
      path: '/miss'
      fullPath: '/miss'
      preLoaderRoute: typeof MissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heart': {
      id: '/heart'
      path: '/heart'
      fullPath: '/heart'
      preLoaderRoute: typeof HeartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-you': {
      id: '/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof ForYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForYouRoute: ForYouRoute,
  HeartRoute: HeartRoute,
  MissRoute: MissRoute,
  PromiseRoute: PromiseRoute,
  RealizedRoute: RealizedRoute,
  WrongRoute: WrongRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
